//예약상태
export const RESERVE_STATUS = {
  RESERVECOMPLETE: 'RESERVECOMPLETE',
  CHECKIN: 'CHECKIN',
  CHECKOUT: 'CHECKOUT',
  CLEANING: 'CLEANING',
  CALCEL: 'CANCEL',
}
export const reservationStatusMap = {
  예약완료: RESERVE_STATUS.RESERVECOMPLETE,
  입실: RESERVE_STATUS.CHECKIN,
  퇴실: RESERVE_STATUS.CHECKOUT,
  청소중: RESERVE_STATUS.CLEANING,
  예약취소: RESERVE_STATUS.CALCEL,
}
export const reservationStatusColorMap = {
  RESERVECOMPLETE: '#34C38F',
  CHECKIN: '#50a5f1',
  CHECKOUT: '#f46a6a',
  CLEANING: '#ff6dd1',
  CALCEL: 'CANCEL',
}

//결제상태
export const PAY_STATUS = {
  NOTPAY: 'NOTPAY',
  PARTIALPAY: 'PARTIALPAY',
  PAYCOMPLETE: 'PAYCOMPLETE',
  REFUNDREQUEST: 'REFUNDREQUEST',
  REFUNDCOMPLETE: 'REFUNDCOMPLETE',
  CANCEL: 'CANCEL',
}
export const payStatusMap = {
  미결제: PAY_STATUS.NOTPAY,
  부분결제: PAY_STATUS.PARTIALPAY,
  결제완료: PAY_STATUS.PAYCOMPLETE,
  환불요청: PAY_STATUS.REFUNDREQUEST,
  환불완료: PAY_STATUS.REFUNDCOMPLETE,
  결제취소: PAY_STATUS.CANCEL,
}

//청소상태
export const CLEANING_STATUS = {
  NOTREQUEST: 'NOTREQUEST',
  REQUEST: 'REQUEST',
  ALLOCATION: 'ALLOCATION',
  WORKING: 'WORKING',
  FINISHED: 'FINISHED',
}
export const cleaningMap = {
  NOTREQUEST: '요청전',
  REQUEST: '청소요청',
  ALLOCATION: '',
  WORKING: '청소중',
  FINISHED: '청소완료',
}
