export const RESERVE_STATUS = {
  RESERVECOMPLETE: 'RESERVECOMPLETE',
  CHECKIN: 'CHECKIN',
  CHECKOUT: 'CHECKOUT',
  CLEANING: 'CLEANING',
  CALCEL: 'CANCEL',
}

export const PAY_STATUS = {
  NOTPAY: 'NOTPAY',
  PARTIALPAY: 'PARTIALPAY',
  PAYCOMPLETE: 'PAYCOMPLETE',
  REFUNDREQUEST: 'REFUNDREQUEST',
  REFUNDCOMPLETE: 'REFUNDCOMPLETE',
  CANCEL: 'CANCEL',
}
